#!/bin/sh

FILE=bazelisk
if [ ! -f "$FILE" ]; then
  if ! [ -x "$(command -v wget)" ]; then
    sudo apt install -y wget
  fi
  wget -cqO - https://github.com/bazelbuild/bazelisk/releases/download/v1.4.0/bazelisk-linux-amd64 > bazelisk
  chmod 755 bazelisk
fi

./bazelisk $@
